

/*
 * @(#)Product.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import ro.ubbcluj.lci.codegen.framework.ocl.BasicConstraintChecker;

public class Product {

	public class ConstraintChecker extends BasicConstraintChecker {

		public void check_Product_invariant_barCode() throws InvariantException {

			String strBarCode = Product.this.barCode;
			boolean bNotEquals = !strBarCode.equals("");
			if (!bNotEquals) {
				throw new InvariantException("Bar code is empty");
			}

		}

		public void check_Product_invariant_name() throws InvariantException {

			String strName = Product.this.name;
			boolean bNotEquals = !strName.equals("");
			if (!bNotEquals) {
				throw new InvariantException("Name is empty");
			}

		}

		public void check_Product_invariant_price() throws InvariantException {

			float fPrice = Product.this.price;
			boolean bGreater = fPrice > 0;
			if (!bGreater) {
				throw new InvariantException("Price is less than 0 (zero)");
			}
		}

	}

	private String barCode;

	private String name;

	private float price;

	public Product(String barCode, String name, float price) {
		super();
		this.barCode = barCode;
		this.name = name;
		this.price = price;
	}

	public String getBarCode() {
		return barCode;
	}

	public String getName() {
		return name;
	}

	public float getPrice() {
		return price;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	public void setName(String name) {
		this.name = name;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Override
	public String toString() {
		return "Product [barCode=" + barCode + ", name=" + name + ", price="
				+ price + "]";
	}

	public void validate() throws InvariantException {
		ConstraintChecker cc = new ConstraintChecker();
		cc.check_Product_invariant_barCode();
		cc.check_Product_invariant_name();
		cc.check_Product_invariant_price();
	}
	
	

}
