
/*
 * @(#)Product.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import ro.ubbcluj.lci.codegen.framework.ocl.BasicConstraintChecker;

/**
 *
 * @author unascribed
 */
public class Product {

    
    public float getPrice() {

        float fPrice = Product.this.price;
        return fPrice;

    }
    
    public Product() {

    }
    
    public class ConstraintChecker extends BasicConstraintChecker {

        
        public void checkConstraints() {

            super.checkConstraints();
            check_Product_barCode();
            check_Product_name();
            check_Product_price();

        }
        
        public void check_Product_barCode() {

            String strBarCode = Product.this.barCode;
            boolean bNotEquals = !strBarCode.equals("");
            if (!bNotEquals) {
                System.err.println("invariant 'barCode' failed for object "+Product.this);
            }

        }
        
        public void check_Product_name() {

            String strName = Product.this.name;
            boolean bNotEquals = !strName.equals("");
            if (!bNotEquals) {
                System.err.println("invariant 'name' failed for object "+Product.this);
            }

        }
        
        public void check_Product_price() {

            float fPrice = Product.this.price;
            boolean bGreater = fPrice > 0;
            if (!bGreater) {
                System.err.println("invariant 'price' failed for object "+Product.this);
            }

        }

    }
    
    private String barCode;
    
    private String name;
    
    private float price;

}
