
/*
 * @(#)SaleAgent.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import ro.ubbcluj.lci.codegen.framework.dt.Integer;
import ro.ubbcluj.lci.codegen.framework.ocl.BasicConstraintChecker;
import ro.ubbcluj.lci.codegen.framework.ocl.CollectionUtilities;
import ro.ubbcluj.lci.codegen.framework.ocl.Ocl;

/**
 *
 * @author unascribed
 */
public class SaleAgent {

    
    public void makeSale(Sale sale) {

    }
    
    public final SaleSystem getJob() {

        return job;
    }
    
    public final void setJob(SaleSystem arg) {

        if (job != arg) {
            SaleSystem temp = job;
            job = null;//to avoid infinite recursions
            if (temp != null) {
                temp.removeSaleAgents(this);
            }
            if (arg != null) {
                job = arg;
                arg.addSaleAgents(this);
            }
        }

    }
    
    public final Set getSales() {

        if (sales == null) {
            return java.util.Collections.EMPTY_SET;
        }
        return java.util.Collections.unmodifiableSet(sales);
    }
    
    public final void addSales(Sale arg) {

        if (arg != null) {
            if (sales == null) {
                sales = new LinkedHashSet();
            }
            sales.add(arg);
        }

    }
    
    public final void removeSales(Sale arg) {

        if (sales != null && arg != null) {
            sales.remove(arg);
        }

    }
    
    public int getId() {

        int nId = SaleAgent.this.id;
        return nId;

    }
    
    public String getName() {

        String strName = SaleAgent.this.name;
        return strName;

    }
    
    public List getSales() {

        List seqSales = SaleAgent.this.getSales();
        return seqSales;

    }
    
    public Set totalSale() {

        List seqSales = SaleAgent.this.getSales();
        Set setAsSet = CollectionUtilities.asSet(seqSales);
        return setAsSet;

    }
    
    public SaleAgent() {

    }
    
    public class ConstraintChecker extends BasicConstraintChecker {

        
        public void checkConstraints() {

            super.checkConstraints();
            check_SaleAgent_invariant();
            check_SaleAgent_invariant0();

        }
        
        public void check_SaleAgent_invariant() {

            int nId = SaleAgent.this.id;
            boolean bIsDefined = Ocl.isDefined(Integer.toInteger(nId));
            int nId0 = SaleAgent.this.id;
            boolean bGreater = nId0 > 0;
            boolean bAnd = bIsDefined && bGreater;
            if (!bAnd) {
                System.err.println("invariant 'invariant' failed for object "+SaleAgent.this);
            }

        }
        
        public void check_SaleAgent_invariant0() {

            String strName = SaleAgent.this.name;
            boolean bNotEquals = !strName.equals("");
            if (!bNotEquals) {
                System.err.println("invariant 'invariant0' failed for object "+SaleAgent.this);
            }

        }

    }
    
    private int id;
    
    private String name;
    
    private SaleSystem job;
    
    private Set sales;

}
