
/*
 * @(#)Bond.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */

/**
 *
 * @author unascribed
 */
public class Bond extends Security {

	
	public float marketValue() {

		return 0;

	}
	
	public Bond() {

	}
	
	private int duration;
	
	private float yield;
	
	private Date expiryDate;

}
