
/*
 * @(#)Cash_Account.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author unascribed
 */
public class Cash_Account {

	
	public void insert(float amount) {

	}
	
	public boolean withDrawal(float amount) {

		return false;

	}
	
	public final Set getPortofolio() {

		if (portofolio == null) {
			return java.util.Collections.EMPTY_SET;
		}
		return java.util.Collections.unmodifiableSet(portofolio);
	}
	
	public final void addPortofolio(Portofolio arg) {

		if (arg != null) {
			if (portofolio == null) {
				portofolio = new LinkedHashSet();
			}
			if (portofolio.add(arg)) {
				arg.setCash_position(this);
			}
		}

	}
	
	public final void removePortofolio(Portofolio arg) {

		if (portofolio != null && arg != null) {
			if (portofolio.remove(arg)) {
				arg.setCash_position(null);
			}
		}

	}
	
	public Cash_Account() {

	}
	
	public Set portofolio;
	
	private float amount;

}
