
/*
 * @(#)Enum.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */

/**
 *
 * @author unascribed
 */
public class Enum {

	
	private Enum() {

	}
	
	public static final Enum buy;
	
	public static final Enum sell;
	static{

		buy = new Enum();
		sell = new Enum();

	}

}
