
/*
 * @(#)Holding.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author unascribed
 */
public class Holding {

	
	public float value() {

		return 0;

	}
	
	public boolean create(Order o) {

		return false;

	}
	
	public final Set getPortofolio() {

		if (portofolio == null) {
			return java.util.Collections.EMPTY_SET;
		}
		return java.util.Collections.unmodifiableSet(portofolio);
	}
	
	public final void addPortofolio(Portofolio arg) {

		if (arg != null) {
			if (portofolio == null) portofolio = new LinkedHashSet();
			if (portofolio.add(arg)) {
				arg.addHoldings(this);
			}
		}

	}
	
	public final void removePortofolio(Portofolio arg) {

		if (portofolio != null && arg != null) {
			if (portofolio.remove(arg)) {
				arg.removeHoldings(this);
			}
		}

	}
	
	public final Security getSecurity() {

		return security;
	}
	
	public final void setSecurity(Security arg) {

		if (security != arg) {
			Security temp = security;
			security = null;//to avoid infinite recursions
			if (temp != null) {
				temp.removeHolding(this);
			}
			if (arg != null) {
				security = arg;
				arg.addHolding(this);
			}
		}

	}
	
	public Holding() {

	}
	
	public Set portofolio;
	
	public Security security;
	
	int number;

}
