
/*
 * @(#)Security.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author unascribed
 */
public abstract class Security {

	
	public abstract float marketValue();
	public final Set getOption() {

		if (option == null) {
			return java.util.Collections.EMPTY_SET;
		}
		return java.util.Collections.unmodifiableSet(option);
	}
	
	public final void addOption(Option arg) {

		if (arg != null) {
			if (option == null) {
				option = new LinkedHashSet();
			}
			if (option.add(arg)) {
				arg.setRefer_to(this);
			}
		}

	}
	
	public final void removeOption(Option arg) {

		if (option != null && arg != null) {
			if (option.remove(arg)) {
				arg.setRefer_to(null);
			}
		}

	}
	
	public final Set getOrder() {

		if (order == null) {
			return java.util.Collections.EMPTY_SET;
		}
		return java.util.Collections.unmodifiableSet(order);
	}
	
	public final void addOrder(Order arg) {

		if (arg != null) {
			if (order == null) {
				order = new LinkedHashSet();
			}
			if (order.add(arg)) {
				arg.setSecurity(this);
			}
		}

	}
	
	public final void removeOrder(Order arg) {

		if (order != null && arg != null) {
			if (order.remove(arg)) {
				arg.setSecurity(null);
			}
		}

	}
	
	public final Set getHolding() {

		if (holding == null) {
			return java.util.Collections.EMPTY_SET;
		}
		return java.util.Collections.unmodifiableSet(holding);
	}
	
	public final void addHolding(Holding arg) {

		if (arg != null) {
			if (holding == null) {
				holding = new LinkedHashSet();
			}
			if (holding.add(arg)) {
				arg.setSecurity(this);
			}
		}

	}
	
	public final void removeHolding(Holding arg) {

		if (holding != null && arg != null) {
			if (holding.remove(arg)) {
				arg.setSecurity(null);
			}
		}

	}
	
	public Security() {

	}
	
	public Set option;
	
	public Set order;
	
	public Set holding;
	
	String name;
	
	float price;

}
