
/*
 * @(#)Sale.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author unascribed
 */
public class Sale {

    
    public final Set getItems() {

        if (items == null) {
            return java.util.Collections.EMPTY_SET;
        }
        return java.util.Collections.unmodifiableSet(items);
    }
    
    public final void addItems(SaleItem arg) {

        if (arg != null) {
            if (items == null) {
                items = new LinkedHashSet();
            }
            items.add(arg);
        }

    }
    
    public final void removeItems(SaleItem arg) {

        if (items != null && arg != null) {
            items.remove(arg);
        }

    }
    
    public final SaleAgent getSaleAgent() {

        return saleAgent;
    }
    
    public final void setSaleAgent(SaleAgent arg) {

        if (saleAgent != arg) {
            SaleAgent temp = saleAgent;
            saleAgent = null;//to avoid infinite recursions
            if (temp != null) {
                temp.removeSales(this);
            }
            if (arg != null) {
                saleAgent = arg;
                arg.addSales(this);
            }
        }

    }
    
    public DateTime getSaleDate() {

        DateTime dateTimeSaleDate = Sale.this.saleDate;
        return dateTimeSaleDate;

    }
    
    public Set getItems() {

        Set setItems = Sale.this.getItems();
        return setItems;

    }
    
    public Sale() {

    }
    
    public String saleId;
    
    private DateTime saleDate;
    
    private void saleAgentId;
    
    private Set items;
    
    private SaleAgent saleAgent;

}
