

/*
 * @(#)Sale.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

public class Sale {
    
    private int saleId;

	private String saleDate;

	private int saleAgentId;

	private Set<SaleItem> items;

	public Sale(int saleId, String saleDate, int saleAgentId, Set<SaleItem> items) {
		super();
		this.saleId = saleId;
		this.saleDate = saleDate;
		this.saleAgentId = saleAgentId;
		this.items = items;
	}

	public final void addItems(SaleItem arg) {

        if (arg != null) {
            if (items == null) {
                items = new LinkedHashSet<SaleItem>();
            }
            items.add(arg);
        }

    }

	public final Set<SaleItem> getItems() {

        if (items == null) {
            return Collections.emptySet();
        }
        return java.util.Collections.unmodifiableSet(items);
    }

	public int getSaleAgentId() {
		return saleAgentId;
	}
    
    public String getSaleDate() {
		return saleDate;
	}
    
    public int getSaleId() {
		return saleId;
	}
    
	public final void removeItems(SaleItem arg) {

        if (items != null && arg != null) {
            items.remove(arg);
        }

    }

	public void setItems(Set<SaleItem> items) {
		this.items = items;
	}
    
	public void setSaleAgentId(int saleAgentId) {
		this.saleAgentId = saleAgentId;
	}
    
	public void setSaleDate(String saleDate) {
		this.saleDate = saleDate;
	}
    
	public void setSaleId(int saleId) {
		this.saleId = saleId;
	}

	@Override
	public String toString() {
		return "Sale [saleId=" + saleId + ", saleDate=" + saleDate
				+ ", saleAgentId=" + saleAgentId + ", items=" + items + "]";
	}
	
}
